### ISSUE TITLE
remove dependency for scikit-image

### ISSUE THREAD

**Issue by thawn** [BiAPoL/biapol-taurus#1]
currently, installing the package from pypy also pulls in scikit-image with its myriad of dependencies.

I presume, this is because of the testing code in the demo notebook (at least that is the only place I found where scikit-image is used)
I think it would be good to remove that dependency.

Is there a way to make setuptools ignore the demo notebook when calculating the dependencies?

**Comment by haesleinhuepf** [comment]
I think we will need scikit-image to implement an `imread` function.

**Comment by thawn** [comment]
Do you think it would make sense to implement the imread function in a separate package that depends on `biapol-taurus`? 

That way, the more general functionality (copy files from the fileserver to a taurus project space) would not have such a huge dependency overhead.

This might also help us in convincing the ZIH to install our package in the default python environments on taurus (which they already suggested in an email to you). We could possibly even hand over maintenance to the ZIH then ;-)

Alternatively, we could move the base fileserver functionality into a separate package. And develop the image specific part here. 

The fileserver-specific package could be called for example `taurus-datamover` (since it is essentially a python wrapper for the [datamover](https://doc.zih.tu-dresden.de/data_transfer/datamover/) shell scripts on taurus).

**Comment by thawn** [comment]
core functionality was moved to [taurus-datamover](https://gitlab.mn.tu-dresden.de/bia-pol/taurus-datamover). image, numpy, and pandas i/o functions were added as optional dependencies (5ad2fa4)
