### ISSUE TITLE
Copy&paste code from a taurus-notebook to a local notebook should work...

### ISSUE THREAD

**Issue by haesleinhuepf** [BiAPoL/biapol-taurus#7]
If I code somethign link this on taurus:
```
imsave("blobs_binary.tif", binary, target="fileserver")
```

and then copy it to my local notebook, that uses skimage, this line would crash because it doesn't know what `target="fileserver"` is.

**Comment by haesleinhuepf** [comment]
What would work though:
```
imsave("blobs_binary.tif", binary)
pft.sync_to_fileserver()
```
see #5

**Comment by thawn** [comment]
this works now. (I removed the target parameter)

**Comment by thawn** [comment]
there still are some open issues, (windows paths and saving to the current working directory), but they are discussed in issue #6.
